#!/usr/bin/env bash
cat <<EOF
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
 "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html lang='en' xml:lang='en' xmlns='http://www.w3.org/1999/xhtml'>
<head>
  <meta content='text/html; charset=utf-8' http-equiv='Content-Type' />
  <meta content='en' http-equiv='Content-Language' />
  <title>Integrity | The easy and fun automated continuous integration server</title>
  <link href='/stylesheets/reset.css' media='screen' rel='stylesheet' type='text/css' />
  <link href='/stylesheets/integrity.css' media='screen' rel='stylesheet' type='text/css'/>
  <link href='/stylesheets/highlighting.css' media='screen' rel='stylesheet' type='text/css'/>
  <link href='http://integrityapp.com/' rel='home' type='text/html' />
  <script src='/javascript/code_highlighter.js' type='text/javascript'></script>
  <script src='/javascript/ruby.js' type='text/javascript'></script>
  <script src='/javascript/shell.js' type='text/javascript'></script>
</head>
<body>
  <div id='header'>
    <h1><a href='/' rel='home'>Integrity</a></h1>
    <h2>the easy and fun automated
    <strong>continuous integration</strong> server</h2>
  </div>
  <div id='content'>
EOF

ruby -e "require 'maruku';
require 'maruku/ext/math'
# Switch off MathML output
MaRuKu::Globals[:html_math_output_mathml] = false
MaRuKu::Globals[:html_math_engine] = 'none'
puts Maruku.new(File.read('src/integrity.markdown')).to_html"

cat <<EOF
<div id='footer'>
  <div class='credits'>
    Integrity is &copy; 2008
    <a href='http://nicolassanguinetti.info'>Nicolás Sanguinetti</a>
    and <a href='http://atonie.org/'>Simon Rozet</a>
  </div>
  <div class='links'>
    <a href='http://integrity.lighthouseapp.com/projects/14308-integrity'>Bugs / Support</a>
        |
    <a href='http://github.com/foca/integrity'>Source Code</a>
  </div>
</div>
<script type='text/javascript'>
  //<![CDATA[
  var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
  document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
  //]]>
  </script>
  <script type='text/javascript'>
    //<![CDATA[
      try {
      var pageTracker = _gat._getTracker("UA-6377994-1");
      pageTracker._trackPageview();
      } catch(err) {}
    //]]>
  </script>
  </body>
</html>

